# =============================================================================
# IMPORTANT: Secrets are read from environment variables!
# =============================================================================
# These are automatically set by GitHub Actions from repository secrets.
# Variables are passed via TF_VAR_* environment variables.
# =============================================================================

# =============================================================================
# Hetzner Cloud
# =============================================================================

variable "hcloud_token" {
  description = "Hetzner Cloud API token (set via TF_VAR_hcloud_token)"
  type        = string
  sensitive   = true
  # No default - must be provided via environment variable
}

variable "server_type" {
  description = "Hetzner server type (e.g., cax11, cax21, cpx21)"
  type        = string
  default     = "cax31"  # 4 vCPU, 8GB RAM (ARM)
}

variable "server_location" {
  description = "Hetzner datacenter location"
  type        = string
  default     = "fsn1"  # Falkenstein, Germany
}

variable "server_image" {
  description = "OS image for the server"
  type        = string
  default     = "ubuntu-24.04"
}

variable "ipv6_only" {
  description = "Use IPv6 only (no public IPv4). Reduces costs by ~€4/month."
  type        = bool
  # NOTE: IPv6-only is currently disabled due to connectivity issues.
  # IPv6-only servers cannot download cloudflared from GitHub or pkg.cloudflare.com
  # (TLS handshake failures over IPv6). See issue #130 for progress on IPv6 support.
  default     = false
}

variable "ssh_public_key_path" {
  description = "Path to SSH public key file (generated by GitHub Actions)"
  type        = string
  # No default - provided by setup-control-plane workflow
}

variable "ssh_private_key_path" {
  description = "Path to SSH private key file (generated by GitHub Actions)"
  type        = string
  # No default - provided by setup-control-plane workflow
}

# =============================================================================
# Cloudflare
# =============================================================================

variable "cloudflare_api_token" {
  description = "Cloudflare API token (set via TF_VAR_cloudflare_api_token)"
  type        = string
  sensitive   = true
  # No default - must be provided via environment variable
}

variable "cloudflare_account_id" {
  description = "Cloudflare Account ID (set via TF_VAR_cloudflare_account_id)"
  type        = string
  # No default - must be provided via environment variable
}

variable "cloudflare_zone_id" {
  description = "Cloudflare Zone ID for your domain"
  type        = string

  validation {
    condition     = can(regex("^[a-f0-9]{32}$", var.cloudflare_zone_id))
    error_message = "Cloudflare zone_id must be a 32-character hex string."
  }
}

variable "domain" {
  description = "Your domain name (e.g., example.com)"
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$", var.domain))
    error_message = "Domain must be a valid domain name (e.g., example.com)."
  }
}

variable "admin_email" {
  description = "Admin email for Cloudflare Access (full access including SSH)"
  type        = string

  validation {
    condition     = can(regex("^[^@]+@[^@]+\\.[^@]+$", var.admin_email))
    error_message = "Admin email must be a valid email address."
  }
}

variable "user_email" {
  description = "Regular user email for Cloudflare Access (all services except SSH). Optional."
  type        = string
  default     = ""
}

variable "admin_username" {
  description = "Admin username for services like Portainer, Uptime Kuma (default: nexus)"
  type        = string
  default     = "nexus"
}

# =============================================================================
# Services
# =============================================================================

variable "services" {
  description = "Map of services to expose via Cloudflare Tunnel"
  type = map(object({
    enabled        = bool
    subdomain      = string
    port           = number
    public         = bool   # true = no auth, false = behind Cloudflare Access
    description    = optional(string, "")
    core           = optional(bool, false)
    image          = optional(string, "")
    support_images = optional(map(string), {})
  }))
  default = {}
}

# =============================================================================
# Firewall Rules (external TCP access)
# =============================================================================

variable "firewall_rules" {
  description = "Firewall rules for external TCP access (e.g., Kafka, PostgreSQL, MinIO S3)"
  type = map(object({
    port       = number
    protocol   = string
    source_ips = list(string)
    dns_record = optional(string, "")
  }))
  default = {}
}

# =============================================================================
# Docker Hub (optional - for increased pull rate limits)
# =============================================================================

variable "dockerhub_username" {
  description = "Docker Hub username (optional, set via TF_VAR_dockerhub_username)"
  type        = string
  default     = ""
}

variable "dockerhub_token" {
  description = "Docker Hub access token (optional, set via TF_VAR_dockerhub_token)"
  type        = string
  sensitive   = true
  default     = ""
}

# =============================================================================
# GitHub (shared with control-plane, declared here to avoid warnings)
# =============================================================================

# =============================================================================
# Hetzner Object Storage (for LakeFS)
# =============================================================================
# Bucket is created in control-plane to survive teardown.
# Server/region are configured in control-plane with sensible defaults.
# Access key and secret key are secrets (stored in GitHub Secrets).

variable "hetzner_object_storage_access_key" {
  description = "Hetzner Object Storage S3 access key (created in Hetzner Console)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "hetzner_object_storage_secret_key" {
  description = "Hetzner Object Storage S3 secret key (created in Hetzner Console)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "hetzner_object_storage_server" {
  description = "Hetzner Object Storage server (from control-plane output)"
  type        = string
  default     = "fsn1.your-objectstorage.com"
}

variable "hetzner_object_storage_region" {
  description = "Hetzner Object Storage region (from control-plane output)"
  type        = string
  default     = "fsn1"
}

variable "hetzner_s3_bucket" {
  description = "Hetzner Object Storage bucket name (from control-plane output)"
  type        = string
  default     = ""
}

variable "hetzner_s3_bucket_general" {
  description = "Hetzner Object Storage bucket (general purpose, from control-plane output)"
  type        = string
  default     = ""
}

variable "hetzner_s3_bucket_pgducklake" {
  description = "Hetzner Object Storage bucket for pg_ducklake Parquet data files (from control-plane output)"
  type        = string
  default     = ""
}

# =============================================================================
# External S3 Storage (optional - for Filestash multi-backend)
# =============================================================================
# Optional S3-compatible storage (e.g., Cloudflare R2, AWS S3, MinIO).
# When configured, auto-mounted as an additional Filestash backend.

variable "external_s3_endpoint" {
  description = "External S3-compatible endpoint URL, e.g. https://<account>.r2.cloudflarestorage.com"
  type        = string
  default     = ""
}

variable "external_s3_region" {
  description = "External S3 region, e.g. auto for R2, us-east-1 for AWS"
  type        = string
  default     = "auto"
}

variable "external_s3_access_key" {
  description = "External S3 access key"
  type        = string
  sensitive   = true
  default     = ""
}

variable "external_s3_secret_key" {
  description = "External S3 secret key"
  type        = string
  sensitive   = true
  default     = ""
}

variable "external_s3_bucket" {
  description = "External S3 bucket name"
  type        = string
  default     = ""
}

variable "external_s3_label" {
  description = "Display label in Filestash for external storage, e.g. 'Cloudflare R2'"
  type        = string
  default     = "External Storage"
}

# =============================================================================
# Cloudflare R2 Datalake (auto-created during setup)
# =============================================================================
# R2 bucket for data storage, auto-configured as primary Filestash backend.
# Created by setup-control-plane, credentials stored as GitHub Secrets.

variable "r2_data_access_key" {
  description = "R2 data bucket access key (auto-generated during setup)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "r2_data_secret_key" {
  description = "R2 data bucket secret key (auto-generated during setup)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "r2_data_bucket" {
  description = "R2 data bucket name (auto-generated during setup)"
  type        = string
  default     = ""
}

variable "persistent_volume_id" {
  description = "Hetzner Cloud Volume ID for persistent storage (from control-plane output, 0 = no volume)"
  type        = number
  default     = 0
}

variable "github_owner" {
  description = "GitHub repository owner (used by control-plane module)"
  type        = string
  default     = ""
}

variable "github_repo" {
  description = "GitHub repository name (used by control-plane module)"
  type        = string
  default     = ""
}
